name: CI

on:
  push:
    branches: [ main, master, test ]
  pull_request:
    branches: [ main, master, test ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v -race ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Check out code
      uses: actions/checkout@v4

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest